export const GET_ALL_POST = "GET_ALL_POST"
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS"
export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE"

export const SEND_ALL_POST = "SEND_ALL_POST"
export const SEND_ALL_POST_SUCCESS = "SEND_ALL_POST_SUCCESS"
export const SEND_ALL_POST_FAILURE = "SEND_ALL_POST_FAILURE"

export const UPDATE_ITEMS_REQUEST = "UPDATE_ITEMS_REQUEST"
export const UPDATE_ITEMS_SUCCESS = "UPDATE_ITEMS_SUCCESS"
export const UPDATE_ITEMS_FAILURE = "UPDATE_ITEMS_FAILURE"

export const DELETE_ITEMS_REQUEST = "DELETE_ITEMS_REQUEST"
export const DELETE_ITEMS_SUCCESS = "DELETE_ITEMS_SUCCESS"
export const DELETE_ITEMS_FAILURE = "DELETE_ITEMS_FAILURE"